### ISSUE TITLE
Missing dependency 'rc-trigger' in package.json

### ISSUE THREAD

**Issue by alienzhangyw** [react-component/tour#16]
Yarn build error:
![image](https://user-images.githubusercontent.com/58874541/202603089-c5e6a6c0-ba44-4a37-babc-418f29e2cc9f.png)

https://github.com/react-component/tour/blob/71333eb25901244f996ba927fcdf2d58cd5c748c/src/Tour.tsx#L4

https://github.com/react-component/tour/blob/71333eb25901244f996ba927fcdf2d58cd5c748c/package.json#L42-L48

**Comment by heiyu4585** [comment]
我试了没复现呢, 可以具体描述下 复现环境么

**Comment by afc163** [comment]
We should add rc-trigger to deps explicitly if we depends on it.

**Comment by alienzhangyw** [comment]
> 我试了没复现呢, 可以具体描述下 复现环境么

使用yarnV3 pnp方式安装create-react-app，添加antdV5，页面加入相关组件，然后运行yarn build打包。
如果你的环境的node_modules里之前有rc-trigger，可能复现不了，但全新安装当前版本的话，因为dependency里面没有，所以yarn不会下载这个包，编译打包的时候就找不到了。
